# Generated by Django 3.1 on 2021-06-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coordinate',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Coordinate',
        ),
    ]
